version: 0.0
os: linux
files:
  - source: ./csye6225-su19-lambda/LambdaApp/target/LambdaApp-1.0-SNAPSHOT.jar
    destination: /opt/tomcat/webapps
hooks:
  BeforeInstall:
    - location: ./removeRoot.sh
      timeout: 3600
      runas: centos
  AfterInstall:
    - location: ./stop_server.sh
      runas: centos
      timeout: 180
  ApplicationStart:
    - location: ./start_server.sh
      timeout: 3600
      runas: centos
