version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-stretch
    steps:
      - checkout
      - run:
          name: Install Packages
          command: |
            sudo apt-get update || sudo apt-get update && sudo apt-get -y install wget zip unzip python3
            python3 --version
      - run:
          name: Install pip
          command: sudo apt install python3-pip
      - run:
          name: Install AWS CLI
          command: |
            pip3 --version
            sudo pip3 install awscli
            aws --version
      - run:
          name: Build Artifact
          command: |
            cd LambdaApp
            pwd
            ls -al
            mvn clean install            
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p email_artifact
            mv /home/circleci/.m2/repository/LambdaApp/LambdaApp/1.0-SNAPSHOT/LambdaApp-1.0-SNAPSHOT.jar email_artifact/
            cd email_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp email_artifact/LambdaApp-1.0-SNAPSHOT.jar s3://${s3bucket}
            # cd email_artifact;  ls -al;aws deploy push --application-name csye6225-webapp --description "Test" --region us-east-1 --s3-location s3://${s3bucket}/LambdaApp-1.0-SNAPSHOT.jar --source email_artifact
            aws lambda update-function-code --function-name resetPassword --region us-east-1 --s3-bucket $(aws s3api list-buckets | jq -r '.Buckets[] | select(.Name | startswith("code-deploy")).Name') --s3-key LambdaApp-1.0-SNAPSHOT.jar

